import "./globals.css";
import { Inter } from "next/font/google";
import { Sora } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const sora = Sora({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "8xFlow Build",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${sora.variable} dark`}>
        {children}
      </body>
    </html>
  );
}
